import {useEffect,useState} from "react";
import type {MatchingWeights,MatchingRule,MatchingRuleState,ModelConnection} from "../../../shared/contracts";

export const defaultWeights:MatchingWeights={skills:35,projects:30,education:15,experience:20};
const labels:Record<keyof MatchingWeights,string>={skills:"技能",projects:"项目经历",education:"学历",experience:"工作经验"};

export function MatchingRulesPage({weights,onApply,workspaceId}:{weights:MatchingWeights;onApply(w:MatchingWeights):void;workspaceId?:string}) {
 const [state,setState]=useState<MatchingRuleState>(),[models,setModels]=useState<ModelConnection[]>([]);
 const [prompt,setPrompt]=useState(""),[name,setName]=useState("我的匹配规则"),[template,setTemplate]=useState("balanced"),[mode,setMode]=useState<"local"|"model">("local"),[connection,setConnection]=useState(""),[limit,setLimit]=useState(20),[draft,setDraft]=useState(weights);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[deleteId,setDeleteId]=useState("");
 function load(rule:MatchingRule){setName(rule.name);setPrompt(rule.prompt);setTemplate(rule.template_id);setMode(rule.mode);setConnection(rule.connection_id||"");setLimit(rule.candidate_limit);setDraft(rule.weights);}
 useEffect(()=>{let off=false;if(workspaceId){setBusy(true);void Promise.all([window.jobfindsme!.matchingRules(workspaceId),window.jobfindsme!.listModelConnections()]).then(([rules,connections])=>{if(off)return;setState(rules);setModels(connections.filter(c=>c.status==="verified"));const active=rules.versions.find(r=>r.rule_version_id===rules.active_rule_id);if(active)load(active);else setPrompt(rules.templates[0].prompt);}).catch(e=>{if(!off)setError(String(e));}).finally(()=>{if(!off)setBusy(false);});}return()=>{off=true;};},[workspaceId]);
 function edit(){setMessage("");}
 const total=Object.values(draft).reduce((a,b)=>a+b,0),valid=total===100&&Object.values(draft).every(v=>Number.isInteger(v)&&v>=0&&v<=100)&&!!prompt.trim()&&!!name.trim()&&(mode==="local"||!!connection);
 async function save(){if(!workspaceId)return;setBusy(true);setError("");try{const rule=await window.jobfindsme!.saveMatchingRule({workspace_id:workspaceId,name,prompt,template_id:template,mode,connection_id:connection||null,candidate_limit:limit,weights:draft});load(rule);onApply({...draft});setState(await window.jobfindsme!.matchingRules(workspaceId));setMessage("已保存并启用新版本；下次检索使用它，历史结果与已有任务保留原规则。");}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function remove(ruleId:string){if(!workspaceId)return;setBusy(true);setError("");try{await window.jobfindsme!.deleteMatchingRule(workspaceId,ruleId);setState(await window.jobfindsme!.matchingRules(workspaceId));setDeleteId("");setMessage("该历史规则已删除。");}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="matching-page"><div className="heading-row matching-heading"><div><h1>匹配规则</h1><p>写下你重视的能力，保存后用于下次匹配。</p></div><button className="primary-button" disabled={!valid||busy||!workspaceId} onClick={()=>void save()}>保存并启用</button></div>
 <section className="panel matching-form"><label>匹配提示词<textarea className="matching-prompt" aria-label="匹配提示词" disabled={busy} maxLength={6000} value={prompt} onChange={e=>{setPrompt(e.target.value);edit();}}/></label>
 <p className="note matching-mode-note">当前评分：{mode==="local"?"本地规则。自由提示词只保存为偏好说明，不参与本地评分；下方权重决定本地分数。":"已选模型。保存后，后续检索会用模型按提示词重排候选，可能产生费用。"}</p>
 <details className="matching-options"><summary>模板、名称与评分设置</summary><div className="matching-option-fields"><label>模板<select aria-label="匹配模板" disabled={busy} value={template} onChange={e=>{const t=state?.templates.find(t=>t.id===e.target.value);if(t){setTemplate(t.id);setPrompt(t.prompt);edit();}}}>{state?.templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}{template==="legacy"&&<option value="legacy">历史权重规则</option>}</select></label><label>规则名称<input value={name} disabled={busy} maxLength={80} onChange={e=>{setName(e.target.value);edit();}}/></label><label>评分方式<select aria-label="评分方式" value={mode} disabled={busy} onChange={e=>{setMode(e.target.value as typeof mode);edit();}}><option value="local">本地规则（不调用模型）</option><option value="model">模型按提示词重排候选</option></select></label>{mode==="model"&&<><label>已验证模型<select aria-label="已验证模型" value={connection} disabled={busy} onChange={e=>{setConnection(e.target.value);edit();}}><option value="">请选择模型</option>{models.map(m=><option key={m.connection_id} value={m.connection_id}>{m.provider} · {m.model_id}</option>)}</select></label><label>最多重排候选<input type="number" min={1} max={20} value={limit} disabled={busy} onChange={e=>{setLimit(Math.max(1,Math.min(20,Number(e.target.value)||1)));edit();}}/></label><p className="note">仅显式保存模型模式后，下次检索才可能调用模型；先显示本地结果，最多重排前 {limit} 个候选。</p></>}<details className="advanced-weights"><summary>本地评分权重 · 合计 {total}%</summary><div className="compact-weights">{(Object.keys(labels) as Array<keyof MatchingWeights>).map(key=><label key={key}>{labels[key]}<input aria-label={`${labels[key]}权重`} type="number" min={0} max={100} value={draft[key]} disabled={busy} onChange={e=>{setDraft(w=>({...w,[key]:Number(e.target.value)}));edit();}}/></label>)}</div></details><button type="button" disabled={busy} onClick={()=>{const t=state?.templates[0];if(t){setTemplate(t.id);setPrompt(t.prompt);setDraft(defaultWeights);setMode("local");setConnection("");edit();}}}>恢复默认草稿</button><p className="note">模型只使用已确认简历的脱敏分析副本；岗位正文不作为指令。</p></div></details>
 <details className="matching-history"><summary>历史规则（{state?.versions.length??0}）</summary>{state?.versions.map(v=><div className="matching-version" key={v.rule_version_id}><span>{v.name} · {new Date(v.created_at).toLocaleString()} {state.active_rule_id===v.rule_version_id?"· 当前启用":""}</span><div className="button-row"><button disabled={busy||!("education" in v.weights)} onClick={()=>{load(v);setMessage("已载入历史内容；保存为新版本后才会启用。");}}>{"education" in v.weights?"载入草稿":"旧版维度仅供历史读取"}</button><button disabled={busy||state.active_rule_id===v.rule_version_id} onClick={()=>setDeleteId(v.rule_version_id)}>删除</button></div>{deleteId===v.rule_version_id&&<div className="history-confirm" role="alert"><p>删除「{v.name}」？当前规则及被历史检索或任务引用的版本不能删除。</p><div className="button-row"><button disabled={busy} onClick={()=>void remove(v.rule_version_id)}>确认删除</button><button disabled={busy} onClick={()=>setDeleteId("")}>取消</button></div></div>}</div>)}</details>
 </section>{message&&<p role="status" className="notice">{message}</p>}{error&&<p role="alert" className="error-message">{error}</p>}</div>;
}
