import test from 'node:test';import assert from 'node:assert/strict';
import {BossCollector} from '../dist-electron/main/boss-collector.js';import {bossSearchUrl,canonicalBossJob} from '../dist-electron/main/boss-page.js';
const job=n=>({title:`Python ${n}`,company:'示例',location:'上海',salary:'K',url:`https://www.zhipin.com/job_detail/${n}.html?securityId=not-exported`});
const page=(jobs,extra={})=>({authenticated:true,loginRequired:false,blocked:null,readable:true,empty:false,ended:false,jobs,...extra});
function driver(pages){let index=0,url='',loads=0,details=0;return {get loads(){return loads},get details(){return details},load:async(u,d)=>{if(d){url=u;details++}else{index=0;loads++}},scroll:async()=>{index=Math.min(index+1,pages.length-1)},read:async d=>d?page([],{detail:{title:'Python',company:'示例',description:'真实岗位职责与要求\n'.repeat(15),url}}):pages[index]};}
test('BOSS city codes and canonical URLs exclude tokens, external origins and fake numeric pages',()=>{const u=new URL(bossSearchUrl('Python & AI','上海市'));assert.equal(u.pathname,'/web/geek/jobs');assert.equal(u.searchParams.get('city'),'101020100');assert.equal(u.searchParams.get('query'),'Python & AI');assert.throws(()=>bossSearchUrl('AI','未核验城市'));assert.equal(canonicalBossJob(job(1).url),'https://www.zhipin.com/job_detail/1.html');assert.equal(canonicalBossJob('https://evil.test/job_detail/1.html'),null);});
test('virtualized cards accumulate before at most two details; cache coalesces identical searches',async()=>{const d=driver([page([job(1),job(2)]),page([job(2),job(3)]),page([job(4)],{ended:true})]),c=new BossCollector(d,0),input={keyword:'Python',city:'上海',maxBatches:3,seconds:30};const p=c.collect(input);assert.equal(p,c.collect(input));const result=await p;assert.equal(result.records.length,4);assert.equal(d.details,2);assert(result.collection.complete);assert(result.records.every(r=>!JSON.stringify(r).includes('securityId')));assert(result.records.every(r=>r.payload.salary===''));assert.equal(result.records.filter(r=>r.payload.detail_level==='list_card').every(r=>r.payload.description===''),true);await c.collect(input);assert.equal(d.loads,1);});
test('no growth is partial, explicit continuation reuses the list, changed context rejects old cursor',async()=>{const d=driver([page([job(1)])]),c=new BossCollector(d,0),input={keyword:'Python',city:'上海',maxBatches:3,seconds:30};const result=await c.collect(input);assert.equal(result.collection.stop_reason,'no_growth');assert(result.collection.cursor);await c.collect({...input,cursor:result.collection.cursor});assert.equal(d.loads,1);await c.collect({...input,keyword:'AI'});await assert.rejects(c.collect({...input,cursor:result.collection.cursor}),/continuation_expired/);});
test('risk after one list batch retains jobs and pauses all future source reads',async()=>{const d=driver([page([job(1)]),page([],{blocked:'安全验证'})]),c=new BossCollector(d,0),input={keyword:'Python',city:'上海',maxBatches:3,seconds:30};const result=await c.collect(input);assert.equal(result.records.length,1);assert.equal(result.collection.failure,'risk_control');assert.equal(result.collection.cursor,null);await assert.rejects(c.collect(input),/risk_control/);assert.equal(d.loads,1);assert.equal(d.details,0);});
test('cancel after first batch retains partial records; queued work is cancelled without extra loads',async()=>{const d=driver([page([job(1)]),page([job(2)])]),c=new BossCollector(d,0),input={keyword:'Python',city:'上海',maxBatches:3,seconds:30};const first=c.collect(input,p=>{if(p.stage==='listing')c.cancel()});const second=c.collect({...input,keyword:'RAG'});assert.equal((await first).records.length,1);assert.equal((await second).collection.stop_reason,'cancelled');assert.equal(d.loads,1);});
test('explicit empty is complete; unreadable or expired session is never an empty success',async()=>{for(const [p,reason] of [[page([],{empty:true}),'complete'],[page([],{authenticated:false,loginRequired:true,readable:false}),'login_required'],[page([],{readable:false}),'source_contract_error']]){const c=new BossCollector(driver([p]),0);const result=await c.collect({keyword:'Python',city:'上海',maxBatches:1,seconds:30});assert.equal(result.collection.stop_reason,reason);assert.equal(result.collection.complete,reason==='complete');}});
test('different searches and selected detail share the same serial worker',async()=>{const d=driver([page([job(1)],{ended:true})]);let active=0,max=0;const load=d.load;d.load=async(...args)=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));await load(...args);active--;};const c=new BossCollector(d,0);await Promise.all([c.collect({keyword:'Python',city:'上海',maxBatches:1,seconds:30}),c.collect({keyword:'RAG',city:'上海',maxBatches:1,seconds:30}),c.readDetail('https://www.zhipin.com/job_detail/2.html')]);assert.equal(max,1);const before=d.details;await c.readDetail('https://www.zhipin.com/job_detail/2.html');assert.equal(d.details,before);});
test('contract failures enter backoff; timeout aborts the driver and returns an honest failure',async()=>{let calls=0;const c=new BossCollector({load:async()=>{calls++;throw Error('source_contract_error:offline')},read:async()=>page([]),scroll:async()=>{}},0);await c.collect({keyword:'AI',city:'上海',maxBatches:1,seconds:5});await assert.rejects(c.collect({keyword:'AI',city:'上海',maxBatches:1,seconds:5}),/source_backoff/);assert.equal(calls,1);let aborted=false;const timeout=new BossCollector({load:async(_u,_d,signal)=>{signal.addEventListener('abort',()=>{aborted=true});await new Promise(()=>{})},read:async()=>page([]),scroll:async()=>{}},0);const result=await timeout.collect({keyword:'AI',city:'上海',maxBatches:1,seconds:1});assert(aborted);assert(!result.collection.complete);assert.equal(result.records.length,0);});
