import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import type {AnalysisPreview,ModelConnection,PromptPatchDecision,PromptSession,ResumeContent,ResumeDraft,ResumeState,ResumeVersion,SearchResultItem} from "../../../shared/contracts";
const sections:Array<[keyof ResumeContent,string]>=[["basic_information","基本信息"],["education","教育经历"],["experience","工作经历"],["projects","项目经历"],["skills","专业技能"]];
const emptyContent=():ResumeContent=>({basic_information:[],education:[],experience:[],projects:[],skills:[]});
function friendly(error:unknown){const text=String(error);if(/conflict|不再|不一致/i.test(text))return "简历或目标岗位已变化，旧建议没有覆盖新版本。请开始新会话。";if(/cancel/i.test(text))return "本轮已取消，已保存的会话和修改保留。";if(/model|模型|API Key|connection/i.test(text))return "模型暂不可用，请检查模型设置；本轮没有形成可用修改。";return "本次操作未完成，已有简历和会话保留。请稍后重试。";}
export function ResumePage({target,onConfigureModels}:{target?:SearchResultItem["job"];onConfigureModels():void}){
 const [state,setState]=useState<ResumeState>(),[draft,setDraft]=useState<ResumeDraft>(),[versions,setVersions]=useState<ResumeVersion[]>([]);
 const [accepted,setAccepted]=useState(new Set<string>()),[corrections,setCorrections]=useState<Record<string,string>>({});
 const [models,setModels]=useState<ModelConnection[]>([]),[connection,setConnection]=useState("");
 const [history,setHistory]=useState<PromptSession[]>([]),[session,setSession]=useState<PromptSession>();
 const [jobs,setJobs]=useState<Array<SearchResultItem["job"]>>([]),[jobId,setJobId]=useState(target?.job_id||"");
 const [targetTitle,setTargetTitle]=useState(target?`${target.company} · ${target.title}`:""),[targetUrl,setTargetUrl]=useState(target?.apply_url||""),[jd,setJd]=useState(target?.description||"");
 const [prompt,setPrompt]=useState(""),[facts,setFacts]=useState(""),[turn,setTurn]=useState(0);
 const [busy,setBusy]=useState(true),[generating,setGenerating]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [editContent,setEditContent]=useState<ResumeContent>(emptyContent),[privacy,setPrivacy]=useState(new Set(["name","phone","email","address","id_number"])),[analysis,setAnalysis]=useState<AnalysisPreview>();
 const [showPreview,setShowPreview]=useState(false),[previewId,setPreviewId]=useState(""),[template,setTemplate]=useState<"classic"|"compact">("classic"),[exporting,setExporting]=useState("");
 const [mobilePane,setMobilePane]=useState("chat");const previewTrigger=useRef<HTMLButtonElement>(null);const dialog=useRef<HTMLElement>(null);const mounted=useRef(true);
 const current=versions.find(v=>v.is_current),base=versions.find(v=>v.version_id===session?.base_version_id),selectedVersion=versions.find(v=>v.version_id===previewId)||current;
 const conflict=!!session&&session.status==="active"&&session.base_version_id!==current?.version_id;
 const editable=!!session&&session.status==="active"&&!conflict&&!draft;
 const locked=busy||generating;const shownPatches=session?.patches.filter(p=>p.turn_number===turn)||[];
 function setDraftState(next:ResumeState){setState(next);setDraft(next.active_draft||undefined);if(next.active_draft){setAccepted(new Set(next.active_draft.facts.map(f=>f.fact_id)));setCorrections(Object.fromEntries(next.active_draft.facts.map(f=>[f.fact_id,f.value])));}}
 async function reload(){const next=await window.jobfindsme!.getResumeState();if(!mounted.current)return;setDraftState(next);if(next.workspace_id){const [v,h,j]=await Promise.all([window.jobfindsme!.listResumeVersions(next.workspace_id),window.jobfindsme!.listPromptSessions(next.workspace_id),window.jobfindsme!.listJobTracking(next.workspace_id)]);if(!mounted.current)return;setVersions(v);setHistory(h);setJobs(j.map(i=>i.job));setEditContent(v.find(i=>i.is_current)?.content||emptyContent());return {next,v,h};}}
 function chooseSession(value:PromptSession){setSession(value);setConnection(value.connection_id);setTargetTitle(value.target_title||"");setTargetUrl(value.target_url||"");setJd(value.target_jd||"");setTurn(Math.max(0,...value.patches.map(p=>p.turn_number)));setFacts("");setMessage("");}
 function updateSession(value:PromptSession){setSession(value);setHistory(old=>[value,...old.filter(s=>s.session_id!==value.session_id)]);setTurn(Math.max(0,...value.patches.map(p=>p.turn_number)));}
 useEffect(()=>{mounted.current=true;setBusy(true);void Promise.all([reload(),window.jobfindsme!.listModelConnections()]).then(([loaded,connections])=>{if(!mounted.current)return;const ready=connections.filter(c=>c.status==="verified"&&(c.has_api_key||c.auth_mode==="none"));setModels(ready);setConnection(ready[0]?.connection_id||"");const previous=loaded?.h.find(s=>s.status==="active"&&s.base_version_id===loaded.next.current_version_id&&(!target||((s.target_jd||"")===(target.description||"")&&(s.target_url||"")===(target.apply_url||""))));if(previous)chooseSession(previous);}).catch(e=>{if(mounted.current)setError(friendly(e));}).finally(()=>{if(mounted.current)setBusy(false);});return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!showPreview)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();setShowPreview(false);}if(e.key==="Tab"){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled),textarea:not(:disabled),[tabindex="0"]')||[]).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener("keydown",key);return()=>{window.removeEventListener("keydown",key);previewTrigger.current?.focus();};},[showPreview]);
 async function action(run:()=>Promise<unknown>){setBusy(true);setError("");try{await run();}catch(e){setError(friendly(e));await reload().catch(()=>{});}finally{setBusy(false);}}
 async function importResume(){await action(async()=>{const value=await window.jobfindsme!.chooseAndImportResume();if(value){await reload();setMessage("请核对解析事实后确认，原有版本暂不改变。");}});}
 async function confirm(){if(!draft)return;await action(async()=>{await window.jobfindsme!.confirmResume({workspace_id:draft.workspace_id,profile_id:draft.profile_id,accepted_fact_ids:[...accepted],corrections:Object.fromEntries([...accepted].map(id=>[id,corrections[id]]))});await reload();setSession(undefined);setMessage("已创建确认版本，可以开始对话修改。");});}
 function newConversation(){setSession(undefined);setTurn(0);setPrompt("");setFacts("");setMessage("新会话将基于当前已确认版本；旧会话仍在历史中。");setMobilePane("chat");}
 async function send(){if(!state?.workspace_id||!current||!connection||!prompt.trim()||draft||conflict)return;setGenerating(true);setError("");const instruction=prompt;try{let active=session;if(!active||active.status!=="active"){active=await window.jobfindsme!.createPromptSession({workspace_id:state.workspace_id,base_version_id:current.version_id,connection_id:connection,target_title:targetTitle,target_url:targetUrl,target_jd:jd});updateSession(active);}const result=await window.jobfindsme!.generatePromptTurn({session_id:active.session_id,prompt:instruction,project_facts:facts.split("\n").map(s=>s.trim()).filter(Boolean),optional_jd:active.target_jd||undefined,redacted_fields:[...privacy]});if(!mounted.current)return;updateSession(result);setPrompt("");setFacts("");setMobilePane("results");setMessage("建议尚未写入简历，请逐段决定。");}catch(e){if(mounted.current){setError(friendly(e));await reload().catch(()=>{});}}finally{if(mounted.current)setGenerating(false);}}
 async function decide(patchId:string,decision:PromptPatchDecision){if(!session)return;await action(async()=>{const value=await window.jobfindsme!.decidePromptPatch(session.session_id,patchId,decision);const selectedTurn=turn;updateSession(value);setTurn(selectedTurn);});}
 async function save(){if(!session)return;await action(async()=>{const v=await window.jobfindsme!.savePromptSession(session.session_id);const loaded=await reload();const saved=loaded?.h.find(s=>s.session_id===session.session_id);if(saved)updateSession(saved);setMessage(`已另存为 v${v.version_number}，原文件和旧版本保留。继续发送会基于新版本开始会话。`);});}
 function evidenceText(id:string){const parts=id.split(":");if(parts[0]==="resume"){const section=sections.find(([key])=>key===parts[1]);return section?`${section[1]}：${base?.content[section[0]][Number(parts[2])-1]||"原始依据暂不可读"}`:"原始依据暂不可读";}if(parts[0]==="user_project"){const facts=[...new Set(session?.messages.flatMap(m=>m.project_facts)||[])];return `已确认补充事实：${facts[Number(parts[1])-1]||"暂不可读"}`;}return "依据暂不可读";}
 async function exportFile(format:"pdf"|"docx"|"md"){if(!state?.workspace_id||!selectedVersion)return;setExporting(format);setError("");try{const result=await window.jobfindsme!.exportResume({workspace_id:state.workspace_id,version_id:selectedVersion.version_id,format,template});if(result)setMessage(`已导出 v${selectedVersion.version_number} · ${format.toUpperCase()}`);}catch(e){setError(friendly(e));}finally{setExporting("");}}
 return <div className="resume-page"><div className="heading-row resume-heading"><div><h1>我的简历</h1><p>通过对话修改，逐段采纳，另存为新版本。</p></div><div className="button-row"><button disabled={locked} onClick={()=>void importResume()}>{current?"导入其他简历":"导入简历"}</button><button ref={previewTrigger} disabled={!current||busy} onClick={()=>{setPreviewId(current?.version_id||"");setShowPreview(true);}}>模板预览</button></div></div>
 {error&&<p className="notice" role="alert">{error}</p>}{message&&<p className="note resume-message" role="status">{message}</p>}
 <div className="resume-mobile-tabs"><button className={mobilePane==="chat"?"selected":""} onClick={()=>setMobilePane("chat")}>对话</button><button className={mobilePane==="results"?"selected":""} onClick={()=>setMobilePane("results")}>修改结果{shownPatches.length?` · ${shownPatches.length}`:""}</button></div>
 <div className="resume-grid"><section className={`resume-conversation ${mobilePane!=="chat"?"resume-mobile-hidden":""}`} aria-label="简历修改对话">
 {!current&&!draft&&<div className="resume-empty"><h2>先导入一份简历</h2><p>支持 PDF、DOCX、MD、TXT。核对内容后，告诉我想怎样修改。</p><button className="primary-button" disabled={busy} onClick={()=>void importResume()}>选择文件并解析</button><p className="note">{state?.capabilities.detail||"扫描 PDF 暂不支持 OCR；旧 DOC 请先转成 DOCX。"}</p></div>}
 {draft&&<section className="resume-confirm"><h2>核对解析结果</h2><p>{draft.file_name} · {draft.facts.length} 条候选事实</p><div className="fact-list">{draft.facts.map(f=><label className="fact-row" key={f.fact_id}><input type="checkbox" checked={accepted.has(f.fact_id)} onChange={e=>setAccepted(old=>{const next=new Set(old);e.target.checked?next.add(f.fact_id):next.delete(f.fact_id);return next;})}/><span>{f.fact_type}</span><textarea value={corrections[f.fact_id]??f.value} disabled={!accepted.has(f.fact_id)} onChange={e=>setCorrections(old=>({...old,[f.fact_id]:e.target.value}))}/></label>)}</div><div className="button-row"><button disabled={locked||!accepted.size} onClick={()=>void confirm()}>确认并创建新版本</button><button disabled={locked} onClick={()=>void action(async()=>{await window.jobfindsme!.abandonResume(draft.workspace_id,draft.profile_id);await reload();})}>放弃本次导入</button></div></section>}
 {current&&<><div className="resume-session-context"><div className="heading-row"><strong>当前简历 v{current.version_number}</strong><button disabled={locked} onClick={newConversation}>新会话</button></div><label>会话历史<select aria-label="会话历史" disabled={locked} value={session?.session_id||""} onChange={e=>{const value=history.find(s=>s.session_id===e.target.value);if(value)chooseSession(value);else newConversation();}}><option value="">新会话 · 当前简历</option>{history.map(s=><option value={s.session_id} key={s.session_id}>{s.target_title||"通用修改"} · {s.messages.length} 轮 · {s.status==="saved"?"已另存":"未另存"}</option>)}</select></label><label>修改模型<select aria-label="修改模型" value={connection} disabled={locked||session?.status==="active"} onChange={e=>setConnection(e.target.value)}><option value="">请选择已测试模型</option>{models.map(m=><option value={m.connection_id} key={m.connection_id}>{m.provider} · {m.model_id}</option>)}</select></label>{!models.length&&<p className="notice">尚未配置可用模型。<button onClick={onConfigureModels}>前往模型设置</button> 配置并测试连接后才能对话修改。</p>}
 <details><summary>目标岗位{targetTitle?` · ${targetTitle}`:"（可选）"}</summary><label>选择已看过岗位<select aria-label="目标岗位" value={session?.status==="active"?"__session":jobId} disabled={locked||session?.status==="active"} onChange={e=>{setJobId(e.target.value);const job=jobs.find(j=>j.job_id===e.target.value);setTargetTitle(job?`${job.company} · ${job.title}`:"");setTargetUrl(job?.apply_url||"");setJd(job?.description||"");}}>{session?.status==="active"&&<option value="__session">{session.target_title||"本会话固定 JD / 通用简历"}</option>}<option value="">通用简历 / 自行补充 JD</option>{jobs.map(j=><option key={j.job_id} value={j.job_id}>{j.company} · {j.title}</option>)}</select></label><label>目标 JD<textarea aria-label="目标 JD" disabled={locked||session?.status==="active"} maxLength={30000} value={jd} onChange={e=>setJd(e.target.value)}/></label><p className="note">JD 仅供参考，不是你的经历。开始会话后目标固定，换岗位请开新会话。</p></details></div>
 {conflict&&<p className="notice">这个会话基于旧版本，不能覆盖当前简历。请点击“新会话”。</p>}
 <div className="resume-messages" aria-live="polite">{session?.messages.map(m=><article className="resume-turn" key={m.turn_number}><div className="chat-user"><small>你 · 第 {m.turn_number} 轮</small><p>{m.user_prompt}</p></div><div className="chat-assistant"><strong>生成了 {session.patches.filter(p=>p.turn_number===m.turn_number).length} 段修改建议</strong>{session.patches.filter(p=>p.turn_number===m.turn_number).flatMap(p=>p.needs_user_input).map((question,i)=><p key={i}>待补充：{question}</p>)}<button onClick={()=>{setTurn(m.turn_number);setMobilePane("results");}}>查看本轮修改</button></div></article>)}</div>
 {!session?.messages.length&&<div className="resume-suggestions"><p>告诉我你希望怎样修改：</p>{["简化表述，保留关键事实","突出项目中的个人贡献","针对目标 JD 调整表达"].map(text=><button key={text} disabled={locked} onClick={()=>setPrompt(text)}>{text}</button>)}</div>}
 <form className="resume-composer" onSubmit={e=>{e.preventDefault();void send();}}><label>修改要求<textarea aria-label="修改要求" placeholder="例如：把项目描述写得更简洁，不增加新经历或指标。" value={prompt} maxLength={4000} disabled={locked||!!draft||conflict} onChange={e=>setPrompt(e.target.value)}/></label><details><summary>补充真实事实 / 隐私设置</summary><label>已确认的补充事实（每行一条）<textarea aria-label="补充真实事实" value={facts} maxLength={20000} disabled={locked} onChange={e=>setFacts(e.target.value)}/></label><p className="note">这里填写的内容将作为你确认的事实；待核实内容请在对话中说明。未采纳建议不会成为事实。</p><div className="privacy-options">{[["name","姓名"],["phone","电话"],["email","邮箱"],["address","地址"],["id_number","身份证"]].map(([key,label])=><label key={key}><input type="checkbox" checked={privacy.has(key)} disabled={locked} onChange={e=>setPrivacy(old=>{const next=new Set(old);e.target.checked?next.add(key):next.delete(key);return next;})}/>过滤{label}</label>)}</div><button type="button" disabled={locked} onClick={()=>void action(async()=>setAnalysis(await window.jobfindsme!.previewAnalysisCopy({workspace_id:state!.workspace_id!,privacy_mode:privacy.size?"redact":"keep",redacted_fields:[...privacy]})))}>查看简历分析副本</button>{analysis&&<pre className="previewtext">{analysis.text}</pre>}<p className="note">默认过滤身份信息。取消全部过滤表示保留；原件不变。</p></details><div className="button-row"><button type="submit" className="primary-button" disabled={locked||!prompt.trim()||!connection||!!draft||conflict}>{generating?"正在生成…":"发送修改要求"}</button>{generating&&<button type="button" onClick={()=>void window.jobfindsme!.cancelPromptTurn().catch(e=>setError(friendly(e)))}>取消生成</button>}</div><p className="note">发送才调用所选模型，可能产生用量。候选修改不会自动写入简历。</p></form>
 <details className="manual-resume-edit"><summary>手动编辑 / 版本历史</summary>{sections.map(([key,label])=><label key={key}>{label}<textarea aria-label={`手动${label}`} value={editContent[key].join("\n")} disabled={locked} onChange={e=>setEditContent(old=>({...old,[key]:e.target.value.split("\n").filter(Boolean)}))}/></label>)}<button disabled={locked} onClick={()=>void action(async()=>{await window.jobfindsme!.saveResumeVersion({workspace_id:state!.workspace_id!,base_version_id:current.version_id,content:editContent});await reload();setMessage("已另存手动编辑，旧会话不能覆盖这个新版本。");})}>手动内容另存新版本</button>{versions.map(v=><p key={v.version_id}>v{v.version_number} · {new Date(v.created_at).toLocaleString()} {v.is_current?"当前":<button disabled={locked} onClick={()=>void action(async()=>{await window.jobfindsme!.restoreResumeVersion(state!.workspace_id!,v.version_id);await reload();})}>回退为新版本</button>}</p>)}</details></>}
 </section><section className={`resume-results ${mobilePane!=="results"?"resume-mobile-hidden":""}`} aria-label="修改结果"><div className="heading-row"><h2>修改结果</h2>{session?.messages.length?<select aria-label="查看轮次" value={turn} onChange={e=>setTurn(Number(e.target.value))}>{session.messages.map(m=><option value={m.turn_number} key={m.turn_number}>第 {m.turn_number} 轮</option>)}</select>:null}</div>
 {session&&<p className="note">基于 v{base?.version_number||"未知"} · {session.target_title||"通用简历"} · {session.status==="saved"?"已另存，旧建议仅供查看":"候选修改，尚未保存"}</p>}
 {!shownPatches.length&&<div className="resume-empty"><h3>{current?"修改建议会显示在这里":"先导入并确认简历"}</h3><p>{current?"发送要求后，逐段比较原文和建议。你决定采纳什么。":"确认真实内容后，即可通过对话简化表述、突出项目或针对岗位调整。"}</p></div>}
 {shownPatches.map(p=><article className={`patch-card ${p.status}`} key={p.patch_id}><div><strong>{sections.find(([key])=>key===p.section)?.[1]}</strong><span>{p.status==="accepted"?"已采纳":p.status==="rejected"?"已拒绝":"待决定"}</span></div><div className="diff before"><b>原文 · 基础版本</b>{p.before.map((text,i)=><p key={i}>{text}</p>)}</div><div className="diff after"><b>建议</b>{p.after.map((text,i)=><p key={i}>{text}</p>)}</div><p className="note">{p.rationale}</p>{p.needs_user_input.length>0&&<div className="notice"><strong>需要补充事实，暂不能采纳</strong>{p.needs_user_input.map((text,i)=><p key={i}>{text}</p>)}<button onClick={()=>{setPrompt("关于上一轮待补充信息：");setMobilePane("chat");}}>继续说明</button></div>}<details><summary>查看引用依据</summary><p className="note">{p.evidence_ids.map(evidenceText).join("；")}</p></details><div className="button-row"><button disabled={locked||!editable||p.needs_user_input.length>0||p.status==="accepted"} onClick={()=>void decide(p.patch_id,"accepted")}>采纳</button><button disabled={locked||!editable||p.status==="rejected"} onClick={()=>void decide(p.patch_id,"rejected")}>拒绝</button>{p.status!=="proposed"&&<button disabled={locked||!editable} onClick={()=>void decide(p.patch_id,"proposed")}>撤销决定</button>}</div></article>)}
 {!!session?.patches.length&&<div className="resume-save"><p className="note">已采纳 {session.patches.filter(p=>p.status==="accepted").length} 段；仅保存已采纳内容。未采纳或待补充内容不会写入。</p><button className="primary-button" disabled={locked||!editable||!session.patches.some(p=>p.status==="accepted")} onClick={()=>void save()}>另存为新版本</button></div>}
 </section></div>
 {showPreview&&createPortal(<div className="modal-backdrop" data-browser-overlay="modal" onClick={()=>setShowPreview(false)}><section ref={dialog} className="resume-preview-dialog" role="dialog" aria-modal="true" aria-label="模板预览" onClick={e=>e.stopPropagation()}><header><h2>模板预览</h2><button autoFocus onClick={()=>setShowPreview(false)} aria-label="关闭模板预览">关闭</button></header><div className="preview-toolbar"><label>预览版本<select aria-label="预览版本" value={selectedVersion?.version_id||""} onChange={e=>setPreviewId(e.target.value)}>{versions.map(v=><option key={v.version_id} value={v.version_id}>v{v.version_number} · {v.is_current?"当前已保存":"历史已保存"}</option>)}</select></label><label>模板<select aria-label="简历模板" value={template} onChange={e=>setTemplate(e.target.value as typeof template)}><option value="classic">经典单栏</option><option value="compact">紧凑单栏</option></select></label></div><p className="note">预览与导出只包含所选已保存版本。当前未保存的采纳结果、其他候选和手动草稿均不包含。</p>{error&&<p role="alert" className="notice">{error}</p>}{message.startsWith("已导出")&&<p role="status">{message}</p>}<div className="resume-preview-scroll"><div className={`resume-preview ${template}`}><h2>简历 · v{selectedVersion?.version_number}</h2>{sections.map(([key,label])=>!!selectedVersion?.content[key].length&&<section key={key}><h4>{label}</h4>{selectedVersion.content[key].map((line,i)=><p key={i}>{template==="classic"?"• ":""}{line}</p>)}</section>)}</div></div><footer><span>导出 v{selectedVersion?.version_number}</span>{(["pdf","docx","md"] as const).map(format=><button key={format} disabled={!!exporting} onClick={()=>void exportFile(format)}>{exporting===format?"导出中…":`导出 ${format.toUpperCase()}`}</button>)}</footer></section></div>,document.body)}
 </div>;
}
