import {hasDiscoveryFilters} from "../../../shared/discovery-filters";
import {salaryPresets,salaryPresetLabel} from "../../../shared/salary-presets";
import {useState} from "react";
import type {SearchFilters as Filters,SourceCapability} from "../../../shared/contracts";
import {PopoverButton} from "../shared/PopoverButton";
const cities="北京 上海 深圳 广州 杭州 成都 南京 苏州 武汉 西安 长沙 重庆 天津 郑州 合肥 厦门 福州 济南 青岛 宁波 无锡 东莞 佛山 珠海 昆明 南宁 贵阳 南昌 石家庄 太原 沈阳 大连 长春 哈尔滨 海口 兰州 银川 西宁 乌鲁木齐 拉萨 呼和浩特 香港 澳门 台北 远程".split(" ");
export function SearchFilters({value,onChange,sources,selectedSources,onSource,onSelectAllSources,onReset}:{value:Filters;onChange(value:Filters):void;sources:SourceCapability[];selectedSources:string[];onSource(id:string,selected:boolean):void;onSelectAllSources(selected:boolean):void;onReset():void}) {
  const [query,setQuery]=useState("");
  const update=(key:keyof Filters,v:unknown)=>onChange({...value,[key]:v});
  const selected=(value.cities??[]).slice(0,1);
  const experience=value.experience_min_years!=null||value.experience_max_years!=null?`${value.experience_min_years??0}–${value.experience_max_years??"不限"}年`:"工作经验";
  const salary=salaryPresetLabel(value);
  const option=(label:string,selected:boolean,action:()=>void)=><button type="button" className={selected?"filter-option selected":"filter-option"} aria-pressed={selected} onClick={action}>{label}{selected&&<span>✓</span>}</button>;
  return <section className="filters"><div className="filter-row compact-filters">
    <PopoverButton title="选择城市" label={selected.length?selected.join("、"):"城市不限"} chosen={!!selected.length} width={340}>{close=><><input aria-label="搜索城市" placeholder="搜索或输入城市" value={query} onChange={e=>setQuery(e.target.value)}/><div className="city-options">{option("不限",!selected.length,()=>{update("cities",[]);close();})}{[...new Set([...cities.filter(c=>c.includes(query.trim())),...(query.trim()?[query.trim()]:[])])].map(city=><button key={city} type="button" aria-pressed={selected.includes(city)} className={selected.includes(city)?"selected":""} onClick={()=>{update("cities",[city]);close();}}>{city}{selected.includes(city)?" ✓":""}</button>)}</div><button className="primary-button" onClick={close}>完成</button></>}</PopoverButton>
    <PopoverButton title="薪资待遇" label={salary} chosen={salary!=="薪资待遇"}>{close=><div className="filter-options" role="group" aria-label="月薪范围（K）">{salaryPresets.map(preset=><div key={preset.label}>{option(preset.label,value.salary_min_k===preset.min&&value.salary_max_k===preset.max,()=>{onChange({...value,salary_min_k:preset.min,salary_max_k:preset.max,salary_mode:"overlap",unknown_policy:"include"});close();})}</div>)}<p className="note">K 表示千元/月；岗位薪资与所选范围有交集即可。薪资未知的岗位会保留待核实。</p></div>}</PopoverButton>
    <PopoverButton title="工作经验" label={experience} chosen={experience!=="工作经验"}>{close=><div className="filter-options">{[[undefined,undefined,"不限"],[0,1,"1年以内"],[1,3,"1–3年"],[3,5,"3–5年"],[5,10,"5–10年"],[10,undefined,"10年以上"]].map(([min,max,label])=><div key={String(label)}>{option(String(label),value.experience_min_years===min&&value.experience_max_years===max,()=>{onChange({...value,experience_min_years:min as number|undefined,experience_max_years:max as number|undefined});close();})}</div>)}</div>}</PopoverButton>
    <PopoverButton title="招聘平台" label={`平台 · 已选 ${selectedSources.length}`} chosen={!!selectedSources.length} width={380}>{close=><div className="source-picker"><div className="source-picker-actions"><span>已选 {selectedSources.length} / {sources.length}</span><button type="button" disabled={!sources.length} onClick={()=>onSelectAllSources(!sources.every(s=>selectedSources.includes(s.source_id)))}>{sources.length&&sources.every(s=>selectedSources.includes(s.source_id))?"取消全选":"全选"}</button></div><fieldset><legend>招聘平台</legend><div className="source-picker-grid">{sources.map(source=><label key={source.source_id}><input type="checkbox" checked={selectedSources.includes(source.source_id)} onChange={e=>onSource(source.source_id,e.target.checked)}/><span>{source.name}<small>{source.live_search_enabled?'可检索':source.login_required&&source.session_status!=='verified'&&source.list_status==='verified'?'列表可读 · 登录待确认':source.login_required&&source.session_status!=='verified'?'登录待确认':'暂不可自动检索'}</small></span></label>)}</div></fieldset><div className="source-picker-footer"><button onClick={()=>{close();window.dispatchEvent(new Event("jfm:show-sources"));}}>检查平台可用性</button><button className="primary-button" onClick={close}>完成 · 已选 {selectedSources.length}</button></div></div>}</PopoverButton>
    <button type="button" className="filter-unread" aria-pressed={value.read==="unread"} onClick={()=>update("read",value.read==="unread"?"any":"unread")}><span aria-hidden="true">{value.read==="unread"?"✓":""}</span>只看未读</button>
    <button type="button" className="clear-filters" title="清空所有筛选，保留搜索关键词" disabled={!hasDiscoveryFilters(value)} onClick={onReset}>清空筛选</button>
  </div></section>;
}
