import {hasDiscoveryFilters} from "../../../shared/discovery-filters";
import {useState} from "react";
import type {SearchFilters as Filters,SourceCapability} from "../../../shared/contracts";
import {PopoverButton} from "../shared/PopoverButton";
const cities="北京 上海 深圳 广州 杭州 成都 南京 苏州 武汉 西安 长沙 重庆 天津 郑州 合肥 厦门 福州 济南 青岛 宁波 无锡 东莞 佛山 珠海 昆明 南宁 贵阳 南昌 石家庄 太原 沈阳 大连 长春 哈尔滨 海口 兰州 银川 西宁 乌鲁木齐 拉萨 呼和浩特 香港 澳门 台北 远程".split(" ");
export function SearchFilters({value,onChange,sources,selectedSources,onSource,onSelectAllSources,onReset}:{value:Filters;onChange(value:Filters):void;sources:SourceCapability[];selectedSources:string[];onSource(id:string,selected:boolean):void;onSelectAllSources(selected:boolean):void;onReset():void}) {
  const [query,setQuery]=useState("");
  const update=(key:keyof Filters,v:unknown)=>onChange({...value,[key]:v});
  const selected=value.cities??[];
  const employment:Record<string,string>={full_time:"全职",internship:"实习",part_time:"兼职",contract:"合同"};
  const experience=value.experience_min_years!=null||value.experience_max_years!=null?`${value.experience_min_years??0}–${value.experience_max_years??"不限"}年`:"工作经验";
  const salary=value.salary_min_k!=null||value.salary_max_k!=null?`${value.salary_min_k??0}–${value.salary_max_k??"不限"}K`:"薪资待遇";
  const option=(label:string,selected:boolean,action:()=>void)=><button type="button" className={selected?"filter-option selected":"filter-option"} aria-pressed={selected} onClick={action}>{label}{selected&&<span>✓</span>}</button>;
  return <section className="filters"><div className="filter-row compact-filters">
    <PopoverButton title="选择城市" label={selected.length?selected.join("、"):"城市不限"} chosen={!!selected.length} width={340}>{close=><><input aria-label="搜索城市" placeholder="搜索或输入城市" value={query} onChange={e=>setQuery(e.target.value)}/><div className="city-options">{option("不限",!selected.length,()=>update("cities",[]))}{[...new Set([...cities.filter(c=>c.includes(query.trim())),...(query.trim()?[query.trim()]:[])])].map(city=><button key={city} type="button" aria-pressed={selected.includes(city)} className={selected.includes(city)?"selected":""} onClick={()=>update("cities",selected.includes(city)?selected.filter(c=>c!==city):[...selected,city])}>{city}{selected.includes(city)?" ✓":""}</button>)}</div><button className="primary-button" onClick={close}>完成</button></>}</PopoverButton>
    <PopoverButton title="薪资待遇" label={salary} chosen={salary!=="薪资待遇"}>{close=><><div className="filter-range"><label>最低月薪<input type="number" min={0} max={1000} aria-label="最低薪资" placeholder="不限" value={value.salary_min_k??""} onChange={e=>update("salary_min_k",e.target.value===""?undefined:Number(e.target.value))}/></label><span>—</span><label>最高月薪<input type="number" min={0} max={1000} aria-label="最高薪资" placeholder="不限" value={value.salary_max_k??""} onChange={e=>update("salary_max_k",e.target.value===""?undefined:Number(e.target.value))}/></label><span>K</span></div><button onClick={()=>onChange({...value,salary_min_k:undefined,salary_max_k:undefined})}>不限</button><button className="primary-button" onClick={close}>完成</button></>}</PopoverButton>
    <PopoverButton title="工作经验" label={experience} chosen={experience!=="工作经验"}>{close=><div className="filter-options">{[[undefined,undefined,"不限"],[0,1,"1年以内"],[1,3,"1–3年"],[3,5,"3–5年"],[5,10,"5–10年"],[10,undefined,"10年以上"]].map(([min,max,label])=><div key={String(label)}>{option(String(label),value.experience_min_years===min&&value.experience_max_years===max,()=>{onChange({...value,experience_min_years:min as number|undefined,experience_max_years:max as number|undefined});close();})}</div>)}</div>}</PopoverButton>
    <PopoverButton title="岗位来源" label={`来源 · 已选 ${selectedSources.length}`} chosen={!!selectedSources.length} width={380}>{close=><div className="source-picker"><p className="note">只选择下次检索的来源；检查可用性需到来源页。</p><div className="source-picker-actions"><button type="button" disabled={sources.length>0&&sources.every(s=>selectedSources.includes(s.source_id))} onClick={()=>onSelectAllSources(true)}>一键勾选全部</button><button type="button" disabled={!selectedSources.length} onClick={()=>onSelectAllSources(false)}>取消全选</button></div>{([['platform','招聘平台'],['company','公司官网']] as const).map(([kind,label])=><fieldset key={kind}><legend>{label}</legend><div className="source-picker-grid">{sources.filter(s=>s.source_type===kind).map(source=><label key={source.source_id}><input type="checkbox" checked={selectedSources.includes(source.source_id)} onChange={e=>onSource(source.source_id,e.target.checked)}/><span>{source.name}<small>{source.live_search_enabled?'可检索':source.login_required&&source.session_status!=='verified'?'需登录 / 检查':'暂不可自动检索'}</small></span></label>)}</div></fieldset>)}<div className="source-picker-footer"><button onClick={()=>{close();window.dispatchEvent(new Event("jfm:show-sources"));}}>检查来源可用性</button><button className="primary-button" onClick={close}>完成 · 已选 {selectedSources.length}</button></div></div>}</PopoverButton>
    <PopoverButton title="更多筛选" label="更多筛选" chosen={!!value.recruitment_track||!!value.employment_type||value.read!=="any"}><div className="filter-extra"><label>求职类型<select value={value.recruitment_track||""} onChange={e=>update("recruitment_track",e.target.value||undefined)}><option value="">不限</option><option value="campus">校招</option><option value="social">社招</option></select></label><label>用工类型<select value={value.employment_type||""} onChange={e=>update("employment_type",e.target.value||undefined)}>{Object.entries({"":"不限",...employment}).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>阅读状态<select value={value.read} onChange={e=>update("read",e.target.value)}><option value="any">全部岗位</option><option value="unread">还没看过</option><option value="read">已看过</option></select></label></div></PopoverButton>
    <button type="button" className="clear-filters" title="清空所有筛选，保留搜索关键词" disabled={!hasDiscoveryFilters(value)} onClick={onReset}>清空筛选</button>
  </div></section>;
}
