import {useEffect,useState} from 'react';
import type {PromptSession} from '../../../shared/contracts';
import {userError} from '../../../shared/user-errors';
const sectionLabels:Record<string,string>={skills:'专业技能',projects:'项目经历',experience:'工作经历',education:'教育经历'};
export function ResumeProposal({workspaceId,sessionId}:{workspaceId:string;sessionId:string}){
 const [session,setSession]=useState<PromptSession>();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;void window.jobfindsme!.listPromptSessions(workspaceId).then(rows=>{if(active)setSession(rows.find(row=>row.session_id===sessionId&&row.workspace_id===workspaceId));}).catch(e=>{if(active)setMessage(userError(e).message);});return()=>{active=false;};},[workspaceId,sessionId]);
 async function decide(id:string,decision:'accepted'|'rejected'){setBusy(true);setMessage('');try{setSession(await window.jobfindsme!.decidePromptPatch(sessionId,id,decision));}catch(e){setMessage(userError(e).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{const version=await window.jobfindsme!.savePromptSession(sessionId);setSession(current=>current&&{...current,status:'saved',saved_version_id:version.version_id});setMessage(`已保存${session?.target_job_id?'岗位专属简历':'简历版本'} ${version.version_number}。`);window.dispatchEvent(new Event('jfm:job-updated'));}catch(e){setMessage(userError(e).message);}finally{setBusy(false);}}
 return <section className="resume-proposal"><h4>简历修改提案</h4><p className="note">{session?.target_job_id?'为这个岗位准备独立副本，基础简历保持不变。':'这里只审阅草稿；接受后仍需点击保存，基础简历才会更新。'}</p>{session?.patches.map(patch=><details key={patch.patch_id} open><summary>{sectionLabels[patch.section]||patch.section} · {patch.status==='accepted'?'已接受':patch.status==='rejected'?'已拒绝':'待审阅'}</summary><div className="proposal-diff"><div><small>修改前</small>{patch.before.map((line,index)=><p key={index}>{line}</p>)}</div><div><small>修改后</small>{patch.after.map((line,index)=><p key={index}>{line}</p>)}</div></div><p>{patch.rationale}</p>{patch.needs_user_input.length>0&&<p className="note">待确认：{patch.needs_user_input.join('；')}。本项不能接受或保存。</p>}<button disabled={busy||session.status!=='active'||patch.needs_user_input.length>0} onClick={()=>void decide(patch.patch_id,'accepted')}>接受</button><button disabled={busy||session.status!=='active'} onClick={()=>void decide(patch.patch_id,'rejected')}>拒绝</button></details>)}{session?.status==='active'&&<button disabled={busy||!session.patches.some(p=>p.status==='accepted')} onClick={()=>void save()}>{session.target_job_id?'保存岗位专属简历':'保存已接受项为新版本'}</button>}{session?.saved_version_id&&<button disabled={busy} onClick={()=>{setBusy(true);void window.jobfindsme!.exportResume({workspace_id:workspaceId,version_id:session.saved_version_id!,format:'pdf',template:'classic'}).catch(e=>setMessage(userError(e).message)).finally(()=>setBusy(false));}}>导出 PDF</button>}{message&&<p className="note" role="status">{message}</p>}</section>;
}
